version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: pki-2fa-service

    ports:
      - "8080:8080"

    environment:
      TZ: "UTC"

    volumes:
      - seed-data:/data
      - cron-output:/cron

      # Mount key files (read-only)
      - ./student_private.pem:/app/student_private.pem:ro
      - ./student_public.pem:/app/student_public.pem:ro
      - ./instructor_public.pem:/app/instructor_public.pem:ro

    restart: unless-stopped

volumes:
  seed-data:
  cron-output:
